server:
  port: 8771
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: schedule-service
        uri: lb://schedule-service
        predicates:
        - Path=/apischedule/**
         
      - id: course-service
        uri: lb://course-service
        predicates:
        - Path=/apicourse/**
        
      - id: test-service
        uri: lb://test-service
        predicates:
        - Path=/apitest/**
       
      - id: student-service
        uri: lb://student-service
        predicates:
        - Path=/apistudent/** 
        
      - id: admin-service
        uri: lb://admin-service
        predicates:
        - Path=/apiadmin/** 
      